using Newtonsoft.Json;

namespace Brio.Docs.HttpConnection
{
    /// <summary>
    /// A machine-readable format for specifying errors in HTTP API responses based on <see href="https://tools.ietf.org/html/rfc7807"/>.
    /// </summary>
    public class ProblemDetails
    {
        /// <summary>
        /// A URI reference [RFC3986] that identifies the problem type. This specification
        /// encourages that, when dereferenced, it provide human-readable documentation for
        /// the problem type (e.g., using HTML [W3C.REC-html5-20141028]). When this member
        /// is not present, its value is assumed to be "about:blank".
        /// </summary>
        [JsonProperty("type", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem type.It SHOULD NOT change from
        /// occurrence to occurrence of the problem, except for purposes of localization(e.g.,
        /// using proactive content negotiation; see[RFC7231], Section 3.4).
        /// </summary>
        [JsonProperty("title", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Title { get; set; }

        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        /// </summary>
        [JsonProperty("status", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public int? Status { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        [JsonProperty("detail", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Detail { get; set; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem.
        /// It may or may not yield further information if dereferenced.
        /// </summary>
        [JsonProperty("instance", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Instance { get; set; }

        /// <summary>
        /// Gets the System.Collections.Generic.IDictionary`2 for extension members.
        /// Problem type definitions MAY extend the problem details object with additional
        /// members. Extension members appear in the same namespace as other members of a
        /// problem type.
        /// </summary>
        [JsonProperty("errors", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public System.Collections.Generic.Dictionary<string, string[]> Errors { get; set; }
    }
}
